/* Generated By:JavaCC: Do not edit this line. AnalyseurConstants.java */
package TaskGeneration;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyseurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int operateur = 5;
  /** RegularExpression Id. */
  int fonction = 6;
  /** RegularExpression Id. */
  int sym = 7;
  /** RegularExpression Id. */
  int parenthO = 8;
  /** RegularExpression Id. */
  int parenthF = 9;
  /** RegularExpression Id. */
  int virgule = 10;
  /** RegularExpression Id. */
  int separateur = 11;
  /** RegularExpression Id. */
  int grammarkeyWords = 12;
  /** RegularExpression Id. */
  int accoladO = 13;
  /** RegularExpression Id. */
  int accoladF = 14;
  /** RegularExpression Id. */
  int RTT = 15;
  /** RegularExpression Id. */
  int timeUnit = 16;
  /** RegularExpression Id. */
  int periodic = 17;
  /** RegularExpression Id. */
  int stochastic = 18;
  /** RegularExpression Id. */
  int time_serie = 19;
  /** RegularExpression Id. */
  int createM = 20;
  /** RegularExpression Id. */
  int updateM = 21;
  /** RegularExpression Id. */
  int createN = 22;
  /** RegularExpression Id. */
  int loi = 23;
  /** RegularExpression Id. */
  int Metric = 24;
  /** RegularExpression Id. */
  int number = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int alpha = 27;
  /** RegularExpression Id. */
  int AppName = 28;
  /** RegularExpression Id. */
  int MetricName = 29;
  /** RegularExpression Id. */
  int param = 30;
  /** RegularExpression Id. */
  int Id = 31;
  /** RegularExpression Id. */
  int Idms = 32;
  /** RegularExpression Id. */
  int url = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<operateur>",
    "<fonction>",
    "<sym>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<separateur>",
    "<grammarkeyWords>",
    "\"{\"",
    "\"}\"",
    "\"RTT\"",
    "<timeUnit>",
    "\"periodic\"",
    "\"stochastic\"",
    "\"time-serie\"",
    "\"CreateMonitor\"",
    "\"UpdateMonitor\"",
    "\"CreateNotifier\"",
    "<loi>",
    "<Metric>",
    "<number>",
    "<DIGIT>",
    "<alpha>",
    "<AppName>",
    "<MetricName>",
    "<param>",
    "<Id>",
    "<Idms>",
    "<url>",
  };

}
